import type { Metadata } from "next";
import { ThemeProvider } from '@/components/theme/ThemeProvider';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={inter.className}>
      <ThemeProvider>
        <Header/>
        {children}
        <Footer/>
      </ThemeProvider>
    </body>
  </html>
  );
}
